CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --use-env --nproc_per_node=1 --master_port=9776 /home/aolivera/TFM-LLM/LLM/Modified-Fastchat/fastchat/train/train_flant5_vision.py \
    --model_name_or_path google/flan-t5-xl \
    --data_path /home/aolivera/TFM-LLM/LLM/Modified-Fastchat/playground/data/train_pretaskData_reduced.json \
    --bf16 True \
    --output_dir ./checkpoints/checkpoints_flant5_pretask_20_epochs_CLIP_unfrozen_eos\
    --num_train_epochs 15 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "epoch" \
    --save_strategy "epoch" \
    --metric_for_best_model "eval_loss" \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --metric_for_best_model "eval_loss" \
    --preprocessed_path ./preprocessed_data/train_processed_pretask_reduced_new_eos.json \
    --gradient_checkpointing True \
